/**
 * Short, standard book-level descriptors (not per-chapter — that would require
 * claims about specific chapter content this app can't respinsibly fabricate
 * for every generated plan). Used to give generated plans' days an evocative
 * title in the same spirit as the hand-authored 365-day plan's daily themes,
 * keyed by the bolls.life/BIBLE_BOOKS id (standard 66-book Protestant order).
 */
export const BOOK_THEMES: Record<number, string> = {
  1: "Creation, Fall, and the Patriarchs",
  2: "Deliverance from Egypt",
  3: "Holiness and the Law of Sacrifice",
  4: "Wilderness Wandering",
  5: "Moses' Final Charge to Israel",
  6: "Conquest of the Promised Land",
  7: "Israel's Cycles of Sin and Deliverance",
  8: "Loyalty and Redemption",
  9: "Israel's First Kings",
  10: "The Reign of David",
  11: "The Divided Kingdom Begins",
  12: "The Fall of Israel and Judah",
  13: "David's Reign Retold",
  14: "The Kings of Judah",
  15: "Return from Exile",
  16: "Rebuilding Jerusalem's Walls",
  17: "Providence in Exile",
  18: "Suffering and the Sovereignty of God",
  19: "Songs of Worship and Lament",
  20: "Wisdom for Daily Life",
  21: "The Search for Meaning",
  22: "A Song of Love",
  23: "Judgment and the Promised Messiah",
  24: "The Weeping Prophet's Warnings",
  25: "Grief over Jerusalem's Fall",
  26: "Visions of Judgment and Restoration",
  27: "Faithfulness Among the Nations",
  28: "God's Unfailing Love for a Wayward People",
  29: "The Day of the LORD",
  30: "A Call for Justice",
  31: "Judgment on Edom",
  32: "God's Mercy to Nineveh",
  33: "Justice, Mercy, and Humility",
  34: "Judgment on Nineveh",
  35: "Trusting God in Troubled Times",
  36: "The Coming Day of Judgment",
  37: "A Call to Rebuild the Temple",
  38: "Visions of a Restored Israel",
  39: "A Call to Covenant Faithfulness",
  40: "Yeshua the Promised King",
  41: "The Servant Who Came to Give His Life",
  42: "The Savior for All People",
  43: "The Word Made Flesh",
  44: "The Spirit-Empowered Church",
  45: "Righteousness by Faith",
  46: "Correcting a Divided Church",
  47: "Ministry Through Weakness",
  48: "Freedom in Messiah",
  49: "The Church, Messiah's Body",
  50: "Joy in Every Circumstance",
  51: "The Supremacy of Messiah",
  52: "Living in Light of His Return",
  53: "Standing Firm Until He Comes",
  54: "Order and Leadership in the Church",
  55: "A Charge to Persevere",
  56: "Sound Doctrine and Good Works",
  57: "Forgiveness Between Brothers",
  58: "Messiah, Greater Than All",
  59: "Faith That Works",
  60: "Hope Amid Suffering",
  61: "Guarding Against False Teachers",
  62: "Walking in the Light",
  63: "Walking in the Truth",
  64: "Hospitality and Faithfulness",
  65: "Contending for the Faith",
  66: "The Return and Reign of Messiah",
};

/** Builds a "{book theme} — {reference}" day title, falling back to the bare reference if a book id is missing/unknown. */
export function themeForBook(bookId: number | undefined, refDisplay: string): string {
  const theme = bookId !== undefined ? BOOK_THEMES[bookId] : undefined;
  return theme ? `${theme} — ${refDisplay}` : refDisplay;
}
